name: Antl compilation

on: [push, pull_request]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: ANTLR prerequisites
        run: sudo apt-get install antlr4
      - name: Compile     
        run: make build
      