name: Antl compilation

on: 
  push:
      branches:
        - master
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: ANTLR prerequisites
        run: |
                sudo apt-get install antlr4
                pip install twine build
      - name: Compile     
        run: make build
      - name: Build and publish
        env:
                TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
                TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
                python3 -m build
                twine upload dist/*
