name: Antl compilation

on: [push, pull_request]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: ANTLR prerequisites
        run: sudo apt-get install antlr4
      - name: Compile     
        run: make build
      - name: Stage compiled files
        run: git add UVLLexer.py UVLListener.py UVLParser.py
      - name: commit changed files
        run: git commit -m "Auto updating compile files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        